server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gpmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 525.xiang

  kafka:
    bootstrap-servers: 192.168.137.131:9092
    consumer:
      group-id: user-service
  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,hystrix.stream
mybatis:
  type-aliases-package: com.fan.gupao.demo.userserviceprovider.mapper.entitys


